let mapel = [
  {
    index: 'admin-mapel',
    route: 'admin-mapel',
    icon:'ph:notebook-fill',
    label:'Data Mata Pelajaran',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'pembagian-mapel',
    route: 'pembagian-mapel',
    icon:'ic:baseline-data-thresholding',
    label:'Pembagian Pengampu',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'penjadwalan-mapel',
    route: 'penjadwalan-mapel',
    icon:'dashicons:schedule',
    label:'Jadwal Pelajaran',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'mapel-dashboard-guru',
    route: 'mapel-dashboard-guru',
    icon:'material-symbols:dashboard',
    label:'Dashboard',
    type:'menu',
    roles:['guru'],
  },
  {
    index: 'mapel-materi',
    route: 'mapel-materi',
    icon:'tabler:book',
    label:'Mata Pelajaran & Materi',
    type:'menu',
    roles:['guru'],
  },
  {
    index: 'mapel-prota',
    route: 'mapel-prota',
    icon:'solar:calendar-outline',
    label:'Prota dan Promes',
    type:'menu',
    roles:['guru'],
  },
  {
    index: 'mapel-rpp',
    route: 'mapel-rpp',
    icon:'carbon:ibm-planning-analytics',
    label:'Generator RPP ',
    type:'menu',
    roles:['guru'],
  },
  {
    index: 'mapel-rpp-history',
    route: 'mapel-rpp-history',
    icon:'ix:history-list',
    label:'Riwayat RPP',
    type:'menu',
    roles:['guru'],
  },
]
export default mapel