let data = [
  {
    index: 'user-management',
    route: 'user-management',
    icon:'ph:notebook-fill',
    label:'Akses Pengguna',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'unit-list',
    route: 'unit-list',
    icon:'fa-solid:school',
    label:'Data Unit Sekolah',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'jurusan-list',
    route: 'jurusan-list',
    icon:'fluent-mdl2:room',
    label:'Data Jurusan',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'teacher-list',
    route: 'teacher-list',
    icon:'mdi:teacher',
    label:'Data Guru',
    type:'menu',
  },
  {
    index: 'kelas-list',
    route: 'kelas-list',
    icon:'mdi:table-chair',
    label:'Data Kelas',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'kamar-list',
    route: 'kamar-list',
    icon:'tabler:bed-filled',
    label:'Data Kamar',
    type:'menu',
    roles:['admin'],
  },
  {
    index: 'santri-list',
    route: 'santri-list',
    icon:'fa-solid:user',
    label:'Data Santri',
    type:'menu',
    roles:['admin','walas'],
  },
  {
    index: 'sesi-list',
    route: 'sesi-list',
    icon:'mdi:timetable',
    label:'Sesi Pembelajaran',
    type:'menu',
    roles:['admin'],
  },
]
export default data