let rapor = [
  {
    index: 'rapor-dashboard',
    route: 'rapor-dashboard',
    icon:'material-symbols:dashboard',
    label:'Dashboard Nilai',
    type:'menu',
    roles:['admin','walas','guru'],
  },
  {
    index: 'teacher-check-raport',
    route: 'teacher-check-raport',
    icon:'mdi:teacher',
    label:'Verifikasi Wali Kelas',
    type:'menu',
  },
  {
    index:'rekap-santri',
    route: 'rekap-santri',
    label:'Kelengkapan Data Santri',
    type:'menu',
    icon:'mdi:account-box-outline',
    roles:['admin','walas'],
  },
  {
    index:'rekap-nilai-uts',
    route: 'rekap-nilai-uts',
    label:'Raport MID',
    type:'menu',
    icon:'icon-park-solid:table-report',
    roles:['admin','walas'],
  },
  {
    index:'rekap-nilai-akhir',
    route: 'rekap-nilai-akhir',
    label:'Raport Akhir',
    type:'menu',
    icon:'icon-park-solid:table-report',
    roles:['admin','walas'],
  },
  {
    index:'rekap-nilai-pengasuhan',
    route: 'rekap-nilai-pengasuhan',
    label:'Raport Pengasuhan',
    type:'menu',
    icon:'icon-park-solid:table-report',
    roles:['admin','walas'],
  },
]
export default rapor