let saving = [
  {
    index: 'presensi-dashboard',
    route: 'presensi-dashboard',
    icon:'material-symbols:dashboard',
    label:'Dashboard',
    type:'menu',
    roles: ['guru','walas'],
  },
  {
    index: 'presensi-admin-dashboard',
    route: 'presensi-admin-dashboard',
    icon:'material-symbols:dashboard',
    label:'Dashboard',
    type:'menu',
    roles: ['admin'],
  },
  {
    index: 'presensi-summary-kedatangan',
    route: 'presensi-summary-kedatangan',
    icon:'lucide:chart-line',
    label:'Rekap Kedatangan',
    type:'menu',
    roles: ['admin'],
  },
  {
    index: 'presensi-summary',
    route: 'presensi-summary',
    icon:'mdi:chart-bar',
    label:'Rekap Kehadiran Kelas',
    type:'menu',
    roles: ['admin'],
  },
  {
    index: 'presensi-izin',
    route: 'presensi-izin',
    icon:'mdi:user-check',
    label:'Pengajuan Izin',
    type:'menu',
    // roles: ['guru'],
  },
  {
    index: 'presensi-report',
    route: 'presensi-report',
    icon:'carbon:report',
    label:'Laporan Guru',
    type:'menu',
    roles: ['guru'],
  },
  {
    index: 'presensi-report-walas',
    route: 'presensi-report-walas',
    icon:'carbon:report',
    label:'Laporan Kelas',
    type:'menu',
    roles: ['walas'],
  },
  {
    index: 'presensi-report-admin',
    route: 'presensi-report-admin',
    icon:'carbon:report',
    label:'Laporan KMI',
    type:'menu',
    roles: ['admin'],
  },
]
export default saving